### ISSUE TITLE
Unable to submit reading for 々

### ISSUE THREAD

**Issue by Sleepy-TF** [Lemmmy/KanjiSchool#25] opened 2024-12-27 13:07 UTC
for some reason, when the 々 kanji shows up I can enter the meaning perfectly fine, but whenever I enter のま as the reading, it always shakes, like when entering a kunyomi instead of onyomi or visa versa. 
If I press "Don't know" it only has のま listed, and entering it on the wanikani website itself works perfectly fine, but it just doesn't wanna work here for some reason.

**Comment by Lemmmy** [comment] 2024-12-27 18:21
I can see that the database entry for 々 updated on the 20th Dec. I can't reproduce the issue myself, so I wonder if this is related to this [recent WaniKani issue](https://community.wanikani.com/t/api-issue-incorrect-kanji-reading-in-3rd-party-apps/68772) that's apparently now fixed?

Please try clicking the menu in the top right, then clicking **Re-sync all data**:
![image](https://github.com/user-attachments/assets/a6f62745-3af4-4af4-9c6e-76788bbf3f70)

Then check again to see if the のま reading is accepted now. You can [add 々 to your study queue](https://kanji.school/kanji/%E3%80%85) to try it straight away.

If this still doesn't work, please share the debug info for the subject:
- Go to [Settings](https://kanji.school/settings) page
- Under **Advanced settings → Debug settings**, turn on **Show debug settings in the subject info screen**
- Return to the [々](https://kanji.school/kanji/%E3%80%85) page
- Scroll to the bottom until you see **JSON dumps**
- Click on **Subject** and scroll to the bottom again
- Click the ![Copy](https://github.com/user-attachments/assets/95e7625a-a1ba-49b2-ad53-f755031ace9a) Copy button
- Paste the code here

**Comment by Sleepy-TF** [comment] 2024-12-27 22:48
All this stuff?? maybe it's that `"accepted_answer": false,` thing

{
  "id": 856,
  "object": "kanji",
  "url": "https://api.wanikani.com/v2/subjects/856",
  "data_updated_at": "2024-12-20T03:25:39.224467Z",
  "data": {
    "created_at": "2012-07-24T23:58:04.630590Z",
    "level": 2,
    "slug": "々",
    "hidden_at": null,
    "document_url": "https://www.wanikani.com/kanji/%E3%80%85",
    "characters": "々",
    "meanings": [
      {
        "meaning": "Repeater",
        "primary": true,
        "accepted_answer": true
      },
      {
        "meaning": "Repetition",
        "primary": false,
        "accepted_answer": true
      },
      {
        "meaning": "Reduplication",
        "primary": false,
        "accepted_answer": true
      },
      {
        "meaning": "Iteration Mark",
        "primary": false,
        "accepted_answer": true
      }
    ],
    "auxiliary_meanings": [
      {
        "meaning": "Kanji Repeater",
        "type": "whitelist"
      },
      {
        "meaning": "Repeater Kanji",
        "type": "whitelist"
      }
    ],
    "readings": [
      {
        "reading": "のま",
        "primary": true,
        "accepted_answer": false,
        "type": "kunyomi"
      }
    ],
    "component_subject_ids": [
      14,
      3
    ],
    "amalgamation_subject_ids": [
      2521,
      2650,
      2669,
      2773,
      3265,
      3427,
      3447,
      3478,
      3510,
      3601,
      4227,
      4232,
      4366,
      4508,
      5048,
      5390,
      5614,
      5843,
      6796,
      6950,
      7388,
      7405,
      7448,
      7517,
      7855,
      7981,
      8095,
      8253,
      8481,
      8493,
      8731,
      8817,
      8843,
      8998,
      9142,
      9165
    ],
    "visually_similar_subject_ids": [],
    "meaning_mnemonic": "This is a strange kanji because it doesn't really mean anything at all. In fact, what it does is it repeats the kanji that comes before it. For example: 人々 is actually 人人. This kanji shows up whenever there's a repeating kanji, because it's often easier to write than writing a more complicated kanji twice. That's why this kanji is the <kanji>repeater</kanji>. It repeats what comes before it.\n\nTo remember that this kanji is the repeater, though, think of a <radical>drop</radical> of water dripping into a <radical>prison</radical>. Drip drop drip drop. It does that over and over again, driving the prisoners nuts. But it never stops. It just repeats over and over.",
    "meaning_hint": "Since this kanji doesn't really have a meaning as much as it does a function, try to change the way you think about it when you're memorizing it.",
    "reading_mnemonic": "This symbol doesn't really have a name, but it's sometimes called the のま because it looks like the katakana characters ノ and マ put together. If you know katakana then this will be easy to read. If you don't, think of it this way:\n\nYour mom is the <kanji>repeater</kanji>. She is trying to force feed you over and over again until you explode (literally). You keep yelling \"<reading>No ma</reading>!\" (のま) but she doesn't stop. She's on a repeating track, never stopping, repeating forever.",
    "reading_hint": "If you feel like you're so full you're about to burst, and if you imagine your mom doing this to you (how could you, ma?), you should be able to remember the reading of this kanji. That being said, the reading is mostly only useful in the event that you have to identify a 々 — otherwise, you won't see it much.",
    "lesson_position": 67,
    "spaced_repetition_system_id": 2
  }
}

**Comment by Lemmmy** [comment] 2024-12-27 22:50
Perfect, thank you!

```json
{
  "readings": [
    {
      "reading": "のま",
      "primary": true,
      "accepted_answer": false,
      "type": "kunyomi"
    }
  ],
}
```

This looks like the bug WaniKani described on their forum; the kanji only has one reading, and it's not an accepted answer `"accepted_answer": false`.

Did you try re-syncing all data? Did that help fix the issue at all?

**Comment by Sleepy-TF** [comment] 2024-12-27 22:52
I did indeed hit the re-sync data button before trying to enter in のま to no avail before sending all the debug info :(

**Comment by Lemmmy** [comment] 2024-12-27 23:01
Strange. Are you on a desktop device? Can you try this:

- Open the developer tools (Usually <kbd>F12</kbd> or <kbd>Ctrl+Shift+I</kbd>) 
- Go to the **Console** tab
- Paste in this code: `localStorage.setItem("kanjischool-subjectsLastSynced", "2024-12-20T02:25:39.224467Z")`
- Press <kbd>Enter</kbd>
- Refresh KanjiSchool
- Try again

**Comment by Sleepy-TF** [comment] 2024-12-27 23:04
this worked, thanks :)

**Closed** 2024-12-27 23:04 UTC
Labels: bug
